apiVersion: apps/v1
kind: Deployment
metadata:
  name: free-create
  labels:
    app: free-create-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: free-create-app
  template:
    metadata:
      labels:
        app: free-create-app
    spec:
      nodeSelector:
        nodePool: cluster
      containers:
        - name: free-create-app
          image: free-create-app:v.01
          ports:
            - containerPort: 8080